// build.zig - GraniteOS: zig build | zig build qemu | zig build qemu-debug

const std = @import("std");

pub fn build(b: *std.Build) void {

    const target = b.resolveTargetQuery(.{

        .cpu_arch = .aarch64,
        .os_tag = .freestanding,
        .abi = .none,

    });

    const optimize = b.standardOptimizeOption(.{});

    // Discovers and builds every *.zig file in user/ (top-level only; user/lib/ is skipped
    // because it contains no entry points and is only imported by user programs).

    // Each binary is copied into a WriteFiles directory alongside a generated
    // user_programs.zig that @embedFile's them all. The kernel imports that module.

    const wf = b.addWriteFiles();

    var src: std.ArrayListUnmanaged(u8) = .{};
    defer src.deinit(b.allocator);

    src.appendSlice(b.allocator,
        \\// Auto-generated by build.zig - do not edit.
        \\pub const Program = struct { name: []const u8, elf: []const u8 };
        \\pub const programs: []const Program = &.{
        \\
    ) catch @panic("OOM");

    // Collect names so we can sort them for reproducible builds.
    var names: std.ArrayListUnmanaged([]const u8) = .{};
    defer names.deinit(b.allocator);

    const user_dir_path = b.pathFromRoot("user");

    var user_dir = std.fs.openDirAbsolute(user_dir_path, .{ .iterate = true })
        catch @panic("cannot open user/");
    defer user_dir.close();

    var iter = user_dir.iterate();

    while (iter.next() catch null) |entry| {

        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".zig")) continue;

        const name = b.allocator.dupe(u8, entry.name[0 .. entry.name.len - 4])
            catch @panic("OOM");
        names.append(b.allocator, name) catch @panic("OOM");

    }

    // Sort for deterministic embed order.

    std.mem.sort([]const u8, names.items, {}, struct {

        fn lt(_: void, a: []const u8, b_str: []const u8) bool {

            return std.mem.lessThan(u8, a, b_str);

        }

    }.lt);

    for (names.items) |name| {

        const source_path = std.fmt.allocPrint(b.allocator, "user/{s}.zig", .{name})
            catch @panic("OOM");

        const user_prog = b.addExecutable(.{

            .name = name,
            .root_module = b.createModule(.{

                .root_source_file = b.path(source_path),
                .target = target,
                .optimize = .ReleaseSmall,
                .single_threaded  = true,

            }),

        });

        user_prog.setLinkerScript(b.path("user/user.ld"));
        user_prog.entry = .{ .symbol_name = "_start" };

        // Copy the compiled binary into the WriteFiles directory under its name.
        _ = wf.addCopyFile(user_prog.getEmittedBin(), name);

        // Append an entry to the generated module source.
        std.fmt.format(src.writer(b.allocator),

            "    .{{ .name = \"{s}\", .elf = @embedFile(\"{s}\") }},\n",
            .{ name, name },

        ) catch @panic("OOM");

    }

    src.appendSlice(b.allocator, "};\n") catch @panic("OOM");

    const embed_src = wf.add("user_programs.zig", src.items);

    const user_programs_mod = b.createModule(.{

        .root_source_file = embed_src,

    });

    // Kernel module

    const kernel_module = b.createModule(.{

        .root_source_file = b.path("kernel/kmain.zig"),
        .target = target,
        .optimize = optimize,
        .single_threaded = true,

    });

    kernel_module.addAssemblyFile(b.path("boot/start.S"));
    kernel_module.addAssemblyFile(b.path("boot/vectors.S"));
    kernel_module.addImport("user_programs", user_programs_mod);

    const kernel = b.addExecutable(.{

        .name        = "kernel",
        .root_module = kernel_module,

    });

    kernel.setLinkerScript(b.path("boot/linker.ld"));

    b.installArtifact(kernel);

    // QEMU run targets

    const qemu_base = [_][]const u8{

        "qemu-system-aarch64",
        "-machine", "virt",
        "-cpu", "cortex-a57",
        "-m", "256M",
        "-display", "none",
        "-serial", "stdio",
        "-kernel", "zig-out/bin/kernel",

    };

    const qemu_cmd = b.addSystemCommand(&qemu_base);
    qemu_cmd.step.dependOn(b.getInstallStep());

    const qemu_step = b.step("qemu", "Run kernel in QEMU");
    qemu_step.dependOn(&qemu_cmd.step);

    const qemu_debug_cmd = b.addSystemCommand(&(qemu_base ++ [_][]const u8{ "-s", "-S" }));
    qemu_debug_cmd.step.dependOn(b.getInstallStep());

    const qemu_debug_step = b.step("qemu-debug", "Run kernel in QEMU with GDB stub on :1234 (halted)");
    qemu_debug_step.dependOn(&qemu_debug_cmd.step);

}
