// build.zig - GraniteOS: zig build | zig build qemu | zig build qemu-debug

const std = @import("std");

pub fn build(b: *std.Build) void {

    const target = b.resolveTargetQuery(.{

        .cpu_arch = .aarch64,
        .os_tag = .freestanding,
        .abi = .none,

    });

    const optimize = b.standardOptimizeOption(.{});

    // Discovers and builds every *.zig file under user/programs/* (see scan_dirs).
    // user/lib/ is skipped because it contains no entry points and is only imported by programs.

    // Each binary is copied into a WriteFiles directory alongside a generated
    // user_programs.zig that @embedFile's them all. The kernel imports that module.

    const write_files = b.addWriteFiles();

    var module_source: std.ArrayListUnmanaged(u8) = .{};
    defer module_source.deinit(b.allocator);

    module_source.appendSlice(b.allocator,
        \\// Auto-generated by build.zig - do not edit.
        \\pub const Program = struct { name: []const u8, elf: []const u8 };
        \\pub const programs: []const Program = &.{
        \\
    ) catch @panic("OOM");

    // Collect (name, source_path) pairs so we can sort them for reproducible builds.
    const SrcEntry = struct { name: []const u8, src: []const u8 };
    var entries: std.ArrayListUnmanaged(SrcEntry) = .{};
    defer entries.deinit(b.allocator);

    const scan_dirs = [_][]const u8{ "user/programs/global", "user/programs/common", "user/programs/fs", "user/programs/location", "user/programs/testers" };

    for (scan_dirs) |dir_rel| {

        const dir_abs = b.pathFromRoot(dir_rel);

        var prog_dir = std.fs.openDirAbsolute(dir_abs, .{ .iterate = true })
            catch @panic("cannot open programs dir");
        defer prog_dir.close();

        var iter = prog_dir.iterate();

        while (iter.next() catch null) |entry| {

            if (entry.kind != .file) continue;
            if (!std.mem.endsWith(u8, entry.name, ".zig")) continue;

            const name = b.allocator.dupe(u8, entry.name[0 .. entry.name.len - 4])
                catch @panic("OOM");
            const src = std.fmt.allocPrint(b.allocator, "{s}/{s}.zig", .{ dir_rel, name })
                catch @panic("OOM");
            entries.append(b.allocator, .{ .name = name, .src = src }) catch @panic("OOM");

        }

    }

    // Sort for deterministic embed order.

    std.mem.sort(SrcEntry, entries.items, {}, struct {

        fn lt(_: void, a: SrcEntry, b_entry: SrcEntry) bool {

            return std.mem.lessThan(u8, a.name, b_entry.name);

        }

    }.lt);

    const syscall_mod = b.createModule(.{

        .root_source_file = b.path("user/lib/syscall.zig"),

    });

    const io_mod = b.createModule(.{

        .root_source_file = b.path("user/lib/io.zig"),

    });

    io_mod.addImport("syscall", syscall_mod);

    const mem_mod = b.createModule(.{

        .root_source_file = b.path("user/lib/mem.zig"),

    });

    mem_mod.addImport("syscall", syscall_mod);

    for (entries.items) |entry| {

        const prog_mod = b.createModule(.{

            .root_source_file = b.path(entry.src),
            .target = target,
            .optimize = .ReleaseSmall,
            .single_threaded  = true,

        });

        prog_mod.addImport("syscall", syscall_mod);
        prog_mod.addImport("io", io_mod);
        prog_mod.addImport("mem", mem_mod);

        const user_prog = b.addExecutable(.{

            .name = entry.name,
            .root_module = prog_mod,

        });

        user_prog.setLinkerScript(b.path("user/linker/user.ld"));
        user_prog.entry = .{ .symbol_name = "_start" };

        // Copies the compiled binary into the WriteFiles directory under its name.
        _ = write_files.addCopyFile(user_prog.getEmittedBin(), entry.name);

        // Appends an entry to the generated module source.
        std.fmt.format(module_source.writer(b.allocator),

            "    .{{ .name = \"{s}\", .elf = @embedFile(\"{s}\") }},\n",
            .{ entry.name, entry.name },

        ) catch @panic("OOM");

    }

    module_source.appendSlice(b.allocator, "};\n") catch @panic("OOM");

    const embed_src = write_files.add("user_programs.zig", module_source.items);

    const user_programs_mod = b.createModule(.{

        .root_source_file = embed_src,

    });

    // Kernel module

    const kernel_module = b.createModule(.{

        .root_source_file = b.path("kernel/kmain.zig"),
        .target = target,
        .optimize = optimize,
        .single_threaded = true,

    });

    kernel_module.addAssemblyFile(b.path("boot/start.S"));
    kernel_module.addAssemblyFile(b.path("boot/vectors.S"));
    kernel_module.addImport("user_programs", user_programs_mod);

    const kernel = b.addExecutable(.{

        .name        = "kernel",
        .root_module = kernel_module,

    });

    kernel.setLinkerScript(b.path("boot/linker.ld"));

    b.installArtifact(kernel);

    // QEMU run targets

    const qemu_base = [_][]const u8{

        "qemu-system-aarch64",
        "-machine", "virt",
        "-cpu", "cortex-a57",
        "-m", "256M",
        "-display", "none",
        "-serial", "stdio",
        "-kernel", "zig-out/bin/kernel",

    };

    const qemu_cmd = b.addSystemCommand(&qemu_base);
    qemu_cmd.step.dependOn(b.getInstallStep());

    const qemu_step = b.step("qemu", "Run kernel in QEMU");
    qemu_step.dependOn(&qemu_cmd.step);

    const qemu_debug_cmd = b.addSystemCommand(&(qemu_base ++ [_][]const u8{ "-s", "-S" }));
    qemu_debug_cmd.step.dependOn(b.getInstallStep());

    const qemu_debug_step = b.step("qemu-debug", "Run kernel in QEMU with GDB stub on :1234 (halted)");
    qemu_debug_step.dependOn(&qemu_debug_cmd.step);

}
